#!/bin/bash
# my-playbook setup script
# Clones the playbook into .playbook/ and appends rules to AI agent files.
#
# Usage:
#   bash setup.sh                    ← run from your project root
#   bash setup.sh /path/to/project   ← or specify a project path

set -e

REPO_URL="https://github.com/signordemola/my-playbook.git"
PROJECT_DIR="${1:-$(pwd)}"
PLAYBOOK_DIR="$PROJECT_DIR/.playbook"
MARKER="# --- my-playbook rules ---"

echo "🔧 Setting up my-playbook in $PROJECT_DIR"

# ─── Clone or update ───────────────────────────────────────────────
if [ -d "$PLAYBOOK_DIR" ]; then
  echo "📦 Playbook already exists. Pulling latest..."
  git -C "$PLAYBOOK_DIR" pull --quiet
else
  echo "📥 Cloning playbook..."
  git clone --quiet "$REPO_URL" "$PLAYBOOK_DIR"
fi

# ─── Build rules block ────────────────────────────────────────────
RULES_BLOCK="$MARKER
# Auto-generated by my-playbook/setup.sh
# Source: https://github.com/signordemola/my-playbook
# Do not edit below this line — re-run setup.sh to update.

"

for rule_file in "$PLAYBOOK_DIR"/rules/*.md; do
  if [ -f "$rule_file" ]; then
    RULES_BLOCK+="$(cat "$rule_file")"
    RULES_BLOCK+=$'\n\n'
  fi
done

RULES_BLOCK+="## Playbooks Available

Reference these in your prompts:
- \`.playbook/playbooks/core/INDEX.md\` — Universal patterns (database, security, auth, etc.)
- \`.playbook/playbooks/booking/INDEX.md\` — Booking platform patterns
- \`.playbook/playbooks/ecommerce/INDEX.md\` — E-commerce patterns
- \`.playbook/playbooks/ui-ux/INDEX.md\` — UI/UX design patterns
- \`.playbook/playbooks/dashboard/INDEX.md\` — Admin dashboard patterns

Use: \"Read .playbook/playbooks/core/INDEX.md and follow those patterns.\"
$MARKER"

# ─── Append to agent files ────────────────────────────────────────
append_rules() {
  local file="$1"
  local filepath="$PROJECT_DIR/$file"

  # If file exists and already has our marker, remove old block first
  if [ -f "$filepath" ] && grep -q "$MARKER" "$filepath"; then
    echo "♻️  Updating $file (replacing old rules)..."
    # Remove everything between the two markers (inclusive)
    sed -i "/$MARKER/,/$MARKER/d" "$filepath"
  else
    echo "📝 Appending rules to $file..."
  fi

  # Create file if it doesn't exist
  touch "$filepath"

  # Append rules block
  echo "" >> "$filepath"
  echo "$RULES_BLOCK" >> "$filepath"
}

append_rules "CLAUDE.md"
append_rules "GEMINI.md"
append_rules "AGENTS.md"

# ─── Add .playbook to .gitignore ──────────────────────────────────
GITIGNORE="$PROJECT_DIR/.gitignore"
if [ -f "$GITIGNORE" ]; then
  if ! grep -q "^\.playbook" "$GITIGNORE"; then
    echo ".playbook/" >> "$GITIGNORE"
    echo "📋 Added .playbook/ to .gitignore"
  fi
else
  echo ".playbook/" > "$GITIGNORE"
  echo "📋 Created .gitignore with .playbook/"
fi

# ─── Done ─────────────────────────────────────────────────────────
echo ""
echo "✅ Done! Your playbook is set up."
echo ""
echo "   Rules appended to: CLAUDE.md, GEMINI.md, AGENTS.md"
echo "   Playbook location: .playbook/"
echo ""
echo "   Tell your AI: \"Read .playbook/playbooks/core/INDEX.md\""
echo ""
